name: dcr_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4




dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - lib/images/
